# Generated by Django 4.0 on 2022-01-02 12:37

from django.db import migrations, models
import django.db.models.deletion
import flogg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(upload_to=flogg.models.upload_products)),
                ('back', models.ImageField(upload_to=flogg.models.upload_products)),
                ('left', models.ImageField(upload_to=flogg.models.upload_products)),
                ('right', models.ImageField(upload_to=flogg.models.upload_products)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flogg.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flogg.category')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flogg.detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
