# Generated by Django 3.2.5 on 2022-01-08 11:13

from django.db import migrations, models
import flogg.models


class Migration(migrations.Migration):

    dependencies = [
        ('flogg', '0002_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='back',
            field=models.ImageField(null=True, upload_to=flogg.models.upload_products),
        ),
        migrations.AlterField(
            model_name='detail',
            name='front',
            field=models.ImageField(null=True, upload_to=flogg.models.upload_products),
        ),
        migrations.AlterField(
            model_name='detail',
            name='left',
            field=models.ImageField(null=True, upload_to=flogg.models.upload_products),
        ),
        migrations.AlterField(
            model_name='detail',
            name='right',
            field=models.ImageField(null=True, upload_to=flogg.models.upload_products),
        ),
    ]
